language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.0
    - android-21
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-21
addons:
  postgresql: "9.3"
notifications:
  email:
    recipients:
      - ntvorennya@gmail.com
    on_success: always
    on_failure: always
before_script:
  - sudo apt-get update
  - sudo apt-get install language-pack-uk
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3
  - psql -c 'create database a;' -U postgres
  - psql -c 'create database d;' -U postgres
script:
  - cd ./server
  - gradle test
  - cd ../droid/
  - gradle check